### ISSUE TITLE
Overhaul tidyverse blogdown setup

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#339]
Catch-all tracking for @batpigandme and @apreshill, to be meted out into individual issues as necessary.

- [x] Page bundling https://github.com/tidyverse/tidyverse.org/issues/279
- [x] Hugo params https://github.com/tidyverse/tidyverse.org/issues/305
- [x] Switch from "Articles" to "Blog" https://github.com/tidyverse/tidyverse.org/issues/340
- [X ] ~Add search https://github.com/tidyverse/tidyverse.org/issues/208~
- [ ] Add tags https://github.com/tidyverse/tidyverse.org/issues/185

**Comment by apreshill** [comment]
Hopefully it's ok if I start adding here too- some issues I noted as relevant to either the Hugo layouts in the base theme itself or to the CSS:

- [ ] Fix hex logos on index page #212 / #95 

- [ ] Display author inside actual blog post #65 

- [ ] Fix size of code within markdown headers (mentioned in #260)

- [ ] Fix vertical padding on code #309

- [ ] Make sure table styling is consistent with #307

**Comment by batpigandme** [comment]
@apreshill, absolutely! That's why it's here! 😄

**Comment by batpigandme** [comment]
Linking to the rest of outstanding issues here
https://github.com/batpigandme/tidyverse.org/issues

**Comment by hadley** [comment]
Closing since these are all down (apart from 185), which we can track separately.
